#!/bin/sh
#
# Kernel post-install hook for dracut.
#
# Arguments passed to this script: $1 pkgname, $2 version.
#
PKGNAME="$1"
VERSION="$2"

if [ ! -x usr/bin/dracut ]; then
	exit 0
fi

# Disable Nvidia
usr/bin/dracut -q --force boot/initramfs.bak ${VERSION}
usr/bin/cat boot/acpi_override boot/initramfs.bak > boot/initramfs-${VERSION}.img
